### ISSUE TITLE
Rowv not working?

### ISSUE THREAD

**Issue by sbcrg** [talgalili/heatmaply#101]
Hi,

I think the "Rowv" argument doesn't work properly. 
In the help page it says "If a vector of integers, then dendrogram is computed and reordered based on the order of the vector."
When I try, it gives a warning and doesn't reorder. 
Simple example:

m <- matrix(1:12,ncol=4)
rownames(m) <- LETTERS[1:3]
heatmaply(m, Rowv=c("A","C", "B"))

Warning message:
In heatmapr(x, row_side_colors = row_side_colors, col_side_colors = col_side_colors,  :
  Invalid value for Rowv, ignoring

sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Mavericks 10.9.5

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] heatmaply_0.11.1   viridis_0.4.0      viridisLite_0.2.0 
[4] plotly_4.7.1       ggplot2_2.2.1.9000

Thanks a lot!

**Comment by Alanocallaghan** [comment]
The argument accepts integers, not letters.

```
heatmaply(m, Rowv=c(1, 3, 2))
```

**Comment by sbcrg** [comment]
Ok right, my mistake for quick reading... Could this be added as a feature to accept character vectors? My rownames are usually gene names or so. That would be useful...
Thanks a lot.

**Comment by Alanocallaghan** [comment]
Internally, this would just match Rowv with the rownames of the input matrix, which is basically all you have to do to convert between character and numeric, ie for your example `Rowv=match(c("A","C", "B"), LETTERS[1:3])`

@talgalili - thoughts?

**Comment by talgalili** [comment]
@sbcrg - could you help explain why you want to use the labels of the original data? Is it because you want the rows to be ordered as closely to the original data as possible? (in which case, why not just use Rowv=FALSE ?). As @Alanocallaghan wrote, we can add this feature, but it would help us understand the use case (both for understanding if this is something that is likely for others to need, and also for how to explain it in the documentation).

Cheers,
Tal
