### ISSUE TITLE
ggheatmp remove row labels does not seem to work

### ISSUE THREAD

**Issue by gtalckmin** [talgalili/heatmaply#248]
Hello Galili,
Great work.
I reckon that 
```
ggheatmap(iris, labRow=NULL)
```
does not remove the row labels.

**Comment by astrasb** [comment]
Disclaimer: I'm a random user, trying to use ggheatmap in her own code.

I managed to "solve" this issue by rewriting line 42 of a local copy of `ggheatmap.R` to read:
 
```
plots <- lapply(plots, function(x) x + theme(plot.margin = unit(c(0, 0, 0, 0), "npc"),
                                                 axis.text.y = element_blank())
                    )
```

It's probably not an ideal fix, but it's hacked away my row labels for now ...

**Comment by Alanocallaghan** [comment]
`ggheatmap(iris, labRow=NULL)` won't remove row labels; `NULL` is actually the default argument value as you can see in usage. Setting it to all NA will. The way to remove row labels is to use showticklabels

Thanks @astrasb - this was useful as a start, though I ended up passing showticklabels to `ggplot_heatmap` instead of your solution, to maintain some separation between the "plot logic" and the "arranging logic" :+1:

**Comment by gtalckmin** [comment]
Hello and thanks for the input.

However:
```
ggheatmap(iris, labRow=NA )
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Either    `ggheatmap(iris,  showticklabels=F )` or  ` ggheatmap(iris,  showticklabels=T )` ouputs the same plot with labels.

@Windows10, R 4.0.2

**Comment by Alanocallaghan** [comment]
By "all NA" I mean a vector of NA values of length nrow(x)

showticklabels must be a vector of length 2, eg `ggheatmap(iris, showticklabels=c(TRUE, FALSE))`
