### ISSUE TITLE
How to change the row_cluster color in heatmaply?

### ISSUE THREAD

**Issue by wwinnerhoo** [talgalili/heatmaply#308]
Hi 

To ensure our heatmap is friendly for color blinders, the default color by setting the row clusters ("k_row = 5") needs to be checked. However, I don't find related information. Could you tell me if your default setting is friendly for them? If not, could you please tell me how to replace the cluster color?  

My code to generate the heatmap is below:

```
heatmaply(matrix_ara,dendrogram = "row",show_dendrogram = TRUE, scale=c("row"),
                      k_row = 5,
                      showticklabels = c(TRUE, FALSE),
                     scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
                       low =    '#0072b2', 
                        high =    '#fc3129'
                     ),
                     # specify the displayed values in the colorbar
                   fontsize_col = 15, fontsize_row = 10, column_text_angle=90 )
```
Thank you in advance!

Best,
Hao

**Comment by alanocallaghan** [comment]
It's actually set in dendextend, not heatmaply. For more info, see `?colorspace::rainbow_hcl` (the current default)

**Comment by talgalili** [comment]
Hi @wwinnerhoo 
In order to control the dendrogram colors you'd need to prepare them "manually" and then pass them to the `Rowv` and `Colv` arguments.
You can see examples of using them here:
https://talgalili.github.io/heatmaply/articles/heatmaply.html

Here is a way to fully reproduce the default order you get from heatmaply, but with alternative colors:


```
library("heatmaply")

# Just like this:
# ggheatmap(mtcars)


library("dendextend")

x  <- as.matrix(datasets::mtcars)

row_dend  <- x %>% 
   dist %>% 
   hclust %>% 
   as.dendrogram %>%
   color_branches( k = 5, col = viridis) %>% 
   seriate_dendrogram(dist(x), method = "OLO")

col_dend  <- x %>% 
   t %>% 
   dist %>% 
   hclust %>% 
   as.dendrogram %>%
   color_branches( k = 2, col = viridis) %>% 
   seriate_dendrogram(dist(t(x)), method = "OLO")

ggheatmap(
   x,
   Rowv = row_dend,
   Colv = col_dend
)

```


![image](https://github.com/talgalili/heatmaply/assets/976006/de71567c-4356-48d6-b1dc-28e69c065071)



p.s.: @alanocallaghan should we add this as an example somewhere?!
