### ISSUE TITLE
cexRow and cexCol do not work

### ISSUE THREAD

**Issue by anniepyim** [talgalili/heatmaply#39]
I could not adjust the font size of labels with cexRow and cexCol. While the layout could adjust the size, font family and font size of the title, it only changes the font family of labels but not the size and color. Are there some ways to work around it?

**Comment by Alanocallaghan** [comment]
This is not a currently accepted parameter. You should be able to adjust this in the layout by adjusting
the axis tickfont https://plot.ly/r/reference/#layout-xaxis-tickfont. Bear in mind there may be multiple axes.

**Comment by Alanocallaghan** [comment]
This will be implemented in a coming release as `cex_row` and `cex_col`

**Comment by talgalili** [comment]
Hi Alan,
A thought: it may be good to keep cexRow and cexCol available also just for
backward compatibility.

**Comment by Alanocallaghan** [comment]
I appreciate the advantage of "backwards compatibility", but I think providing multiple versions of too many parameters can bloat the documentation and code, with little to gain. 

Personally, I would rather a short parameter name such as `fontsize_row` or `fontsize_col` for consistency with the naming of other parameters (underscores, no CamelCase). Similarity to ggplot2 params would also be an option

**Comment by talgalili** [comment]
I would generally agree with you, but since gplots::heatmaply.2 is so
common, I do believe we should help users in supporting their parameters
out of the box.
In terms of a bloated help file, there are nice ways to merge the names to
be side by side.
For example, notice how in:
?heatmaply::heatmaply
The parameters
ColSideColors, RowSideColors
are displayed.
I think a similar grouping should be done to other parameters, and believe
this would allow us to keep this manageable.

**Comment by Alanocallaghan** [comment]
I notice that this is sort of already implemented as `x/yaxis_font_size`, which should also be affected by `cexRow/Col`. However, this is in `heatmapr` and it is not used elsewhere in the code. It doesn't make sense for this parameter to be here, as this function mainly performs clustering and re-ordering. 

This perhaps points to a wider issue of unused parameters, duplicated code, and lack of clear encapsulation. It is worth deciding exactly what each function needs to do.

**Comment by talgalili** [comment]
Hi @Alanocallaghan 
The original premise was to have heatmapr create the needed objects for creating the heatmap, and then for heatmaply to make the plot (and maybe also implement a ggheatmap function, but that is less urgent).
As time passed I realized that people don't read the help file in heatmapr, so I moved to explicitly stating many of the parameters explicitly in heatmaply (although they are merely passed to heatmapr).
On top of that, I wanted to keep backward compatibility with heatmap.2 (and other similar functions), since this would make it easier for users to adopt heatmaply.
I understand there is a lot of cleaning and refactoring that can be made, I am open to suggestions.

Thanks,
Tal

**Comment by Alanocallaghan** [comment]
I think separating the data processing from plotting makes a lot of sense. It seems like `heatmapr` should not deal with graphical options or parameters, merely with data. We can then keep the `heatmapr` class minimal, and potentially write different plot methods for `heatmapr` objects which would all take the same parameter names. It might make sense to have a deeper discussion about where the package might go in future, as this will affect the design decisions.

**Comment by talgalili** [comment]
This is now indeed solved. Great job @Alanocallaghan 

```r
library(heatmaply)
heatmaply(mtcars, fontsize_col = 20, fontsize_row = 5, margin = c(100,90))
```

![image](https://cloud.githubusercontent.com/assets/976006/24859209/49037e9a-1df8-11e7-8a1d-64384d3ddc77.png)
