### ISSUE TITLE
col labels are cut

### ISSUE THREAD

**Issue by stanstrup** [talgalili/heatmaply#5]
For every plot I try the col labels are cut so you can only see the top of the letters.

**Comment by talgalili** [comment]
Hi @stanstrup 
This is a problem with plotly failing to find the correct margins. This can be manually fixed, here is an example:

```r
library(heatmaply)
heatmaply(mtcars) %>% layout(margin = list(l = 130, b = 40))
```

I hope this will be resolved in the future in plotly itself.

Cheers,
Tal

**Comment by talgalili** [comment]
@Alanocallaghan 
Is there any chance that heatmaply could detect the proper margins automatically?

**Comment by Alanocallaghan** [comment]
Difficult, as it's a combination of font size and max label length, but possibly doable

**Comment by Alanocallaghan** [comment]
It's actually very easy and I have implemented it in the `labels` branch, but unfortunately it tends to over-estimate due to letters like "I","l", "j", etc. You could get around this by using a monospace font by default but they generally look ugly as all hell so I'd be reluctant to. Still better than labels being cut off by default imo

**Comment by Alanocallaghan** [comment]
Closing, will continue discussion of labels in #62 if there are any further issues
